# Generated by Django 4.2.3 on 2023-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_bookmark_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="url",
            field=models.URLField(max_length=2000),
        ),
    ]
